### ISSUE TITLE
Site does not look well in small widths

### ISSUE THREAD

**Issue by juanca** [mavenlink/design-system#31]
Looks like some of our pages are missing some styling or better responsive styling. We should consider what are our minimum width and maximum widths. 

Large width: 
![Screen Shot 2019-07-15 at 5 24 42 PM](https://user-images.githubusercontent.com/841084/61257346-83e59300-a725-11e9-9679-8aeffdeab978.png)

Small width:
![Screen Shot 2019-07-15 at 5 24 53 PM](https://user-images.githubusercontent.com/841084/61257347-83e59300-a725-11e9-82fd-bb20f958632a.png)

**Comment by roblevintennis** [comment]
Let's discuss this. I'm wondering if dev tools docked right has something to do with this as I recall we had some media query stuff in there for the internal design system. Again, probably a standup conversation or something.
