### ISSUE TITLE
Consider changing hex colors into RGB values

### ISSUE THREAD

**Issue by juanca** [mavenlink/design-system#44]
Using RGB values will* allow others to use the MDS colors in color functions.

https://stackoverflow.com/questions/40010597/how-do-i-apply-opacity-to-a-css-color-variable

*We need to verify this statement.

**Comment by roblevintennis** [comment]
Yeah, applying `opacity` will affect all areas of the component e.g. background, color, border, outline, etc., will all be "faded" if you apply `opacity: .6;` or similar. Having the colors as `rgb` would allow you to control for say just the font color. I really like this idea 👍

**Comment by juanca** [comment]
Thoughts about existing greys:

Those colors already have alphas but perhaps we should convert them into RGB values so we can modify alphas on usages. Or, was the intention for the colors to be slightly transparent? How does it work when you apply it to the background color of a element that should not be see through?
